inbo/craywatch

- pages/404.md
> Improve link to homepage in 404

- _data/navigation.yml
I fixed the species drop-down list to have all 8 species that we wanted in it (if I did it right that is).
> Fix species dropdown list

- _data/navigation.yml
- pages/aanmelden.md
- pages/locaties-selecteren.md
- pages/locaties.md
Pagina 'aanmelden' en 'instructies' toevoegen en de naam van 'locaties' veranderen naar 'locaties selecteren'
> Pagina's in navigatiebalk aanpassen

- pages/home.md
> Update naam op homepage.md

- _data/footer.yml
Changed list of 2 partners to "dit is een project van het INBO
> Change partner name in footer

- _data/team.yml
> Change layout team description

- _data/team.yml
> Revert "Change layout team description"

- _data/team.yml
> Change description team member

- _data/team.yml
> Revert "Change description team member"

- _data/navigation.yml
'Locaties selecteren' verwijderen en 'Hoe waarnemen' vervangen door Instructies.
> 'Doe mee' list updaten

- pages/aanmelden.md
> Inhoud voor aanmeld pagina

- pages/soorten/faxonius-limosus.md
This reverts commit e066740fa6736d6cc5bb47190f02e872833be63e.
> Revert "Update faxonius-limosus.md"

- pages/home.md
> Update picture home.md

- pages/soorten/procambarus-acutus.md
> Link word rostrum to determinatie

- _config.yml
> Update link colour

- pages/soorten/astacus-astacus.md
> Fotos overzicht soorten

- pages/waarnemingen.md
> Update waarnemingen page

- pages/soorten/astacus-astacus.md
- pages/soorten/faxonius-limosus.md
- pages/soorten/faxonius-virilis.md
- pages/soorten/pacifastacus-leniusculus.md
- pages/soorten/pontastacus-leptodactylus.md
- pages/soorten/procambarus-acutus.md
- pages/soorten/procambarus-clarkii.md
- pages/soorten/procambarus-virginalis.md
Fix #211
Remove all `<br>`
Remove all `.rounded`
> Use `clearfix` for float

- _layouts/map.html
This PR fixes #251 by adding a legend with the right colors mentioned in https://github.com/inbo/craywatch/issues/209#issuecomment-2162424001.
> Add legend

- _layouts/map.html
This PR:
- adds some potentially useful backgrounds
- remove the ones which are not good (too much contrast)
- add alt text for screen readers
> Improve map

- _layouts/map.html
> Clustering size circles

- R/Select_Localities.R
- assets/Localities.csv
Fixed bug that created duplicate locID generation for newly added points by going rowwise & using highest number of loc_id within the same postcode
> Loc id code

- _layouts/map.html
This PR solves #284 by leaving the pane with layers open by default.
> Do not collapse pane layers
